actors:
  moyuru:
    image_url: /images/actors/moyuru.png
    name: Moyuru
    url: https://twitter.com/MoyuruAizawa
  salvador:
    image_url: /images/actors/salvador.png
    name: Salvador
    url: https://twitter.com/MasashiSalvador
  mami:
    image_url: /images/actors/mami.png
    name: Mami
    url: https://cinematic.fm
  yusuke:
    image_url: /images/actors/yusuke.png
    name: Yusuke
    url: https://twitter.com/__yu81__
author: Cinematic.fm
description: 映画について話します。
description_long: MoyuruとSalvadorが映画について話すポッドキャスト
email: lvla0805@gmail.com
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics: UA-128570244-2
hashtag: cinematicfm
itunes_podcast_url: https://podcasts.apple.com/jp/podcast/cinematic-fm/id1464481255
keywords: Cinema, Movie, Film
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: Cinematic.fm
url: https://cinematic.fm
